[general]
search_limit = 7
output_directory = "~/Documents/Photos/posters/moosic"

[credentials]
client_id = "1bf9dda285d84dd88245881c263843fc"
client_secret = "4f4657235903498cb9e76d81091d524a"
genius_access_token = "ZVWek-GoE_uYaGSBDF6_ookFXSKAj0dMLo7zp5Penxb9iSY9l_AIKjvq1x8XNTgk"
